export const LOG_PLOG = 'LOG_PLOG';

export const PLOGS_UPDATED = 'PLOGS_UPDATED';
export const PLOG_UPDATED = 'PLOG_UPDATED';
export const LOCAL_PLOGS_UPDATED = 'LOCAL_PLOGS_UPDATED';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_DATA = 'USER_DATA';

export const SET_PREFERENCES = 'SET_PREFERENCES';

export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SET_USER_FIELD = 'SET_USER_FIELD';

export const START_LOCATION_WATCH = 'START_LOCATION_WATCH';
export const STOP_LOCATION_WATCH = 'STOP_LOCATION_WATCH';
export const LOCATION_CHANGED = 'LOCATION_CHANGED';
