export const LOG_PLOG = 'LOG_PLOG';
export const LOG_PLOG_ERROR = 'LOG_PLOG_ERROR';
export const PLOG_LOGGED = 'PLOG_LOGGED';
export const DELETE_PLOG = 'DELETE_PLOG';
export const DELETE_PLOG_ERROR = 'DELETE_PLOG_ERROR';
export const PLOG_DELETED = 'PLOG_DELETED';

export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';

export const LIKE_PLOG = 'LIKE_PLOG';
export const LIKE_PLOG_ERROR = 'LIKE_PLOG_ERROR';
export const REPORT_PLOG = 'REPORT_PLOG';
export const REPORT_PLOG_ERROR = 'REPORT_PLOG_ERROR';

export const LOAD_HISTORY = 'LOAD_HISTORY';
export const PLOGS_UPDATED = 'PLOGS_UPDATED';
export const LOAD_LOCAL_HISTORY = 'LOAD_LOCAL_HISTORY';
export const LOCAL_HISTORY_LOADING = 'LOCAL_HISTORY_LOADING';
export const PLOG_DATA = 'PLOG_DATA';

export const LOAD_PLOGS = 'LOAD_PLOGS';
export const UNLOAD_PLOGS = 'UNLOAD_PLOGS';

export const SET_REGION = 'SET_REGION';
export const LOCAL_PLOG_IDS = 'LOCAL_PLOG_IDS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_DATA = 'USER_DATA';

export const SET_PREFERENCES = 'SET_PREFERENCES';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const AUTH_CANCELED = 'AUTH_CANCELED';

export const USER_EMAIL_CONFIRMED = 'USER_EMAIL_CONFIRMED';
export const ACTION_CODE_ERROR = 'ACTION_CODE_ERROR';
export const SET_USER_FIELD = 'SET_USER_FIELD';

export const START_LOCATION_WATCH = 'START_LOCATION_WATCH';
export const STOP_LOCATION_WATCH = 'STOP_LOCATION_WATCH';
export const LOCATION_CHANGED = 'LOCATION_CHANGED';
export const LOCATION_ERROR = 'LOCATION_ERROR';
export const LOCATION_INFO = 'LOCATION_INFO';

export const FLASH = 'FLASH';
export const PAUSE_MESSAGES = 'PAUSE';
